pragma ComponentBehavior: Bound

import qs.components.effects
import qs.services
import qs.config
import qs.utils
import Quickshell.Services.SystemTray
import QtQuick

MouseArea {
    id: root

    required property SystemTrayItem modelData

    acceptedButtons: Qt.LeftButton | Qt.RightButton
    hoverEnabled: true
    cursorShape: Qt.PointingHandCursor
    implicitWidth: Config.bar.sizes.iconSize
    implicitHeight: Config.bar.sizes.iconSize

    onClicked: event => {
        if (event.button === Qt.LeftButton)
            modelData.activate();
        else
            modelData.secondaryActivate();
    }

    ColouredIcon {
        id: icon

        anchors.fill: parent
        source: Icons.getTrayIcon(root.modelData.id, root.modelData.icon)
        // m3tertiary matches PillContainer's foreground — a recoloured tray icon
        // sits inline with the status glyphs, so a separate tone reads as a
        // mismatch rather than a rank. Rationale on PillContainer.colour.
        colour: Colours.palette.m3tertiary
        // A DESIGN CHOICE, not a per-app workaround: the shell's surface material
        // is machined metal and the bar carries exactly one chromatic accent (the
        // power glyph), so tray icons are flattened to the palette foreground on
        // purpose. The cost is real and deliberate — Colouriser runs colorization
        // at full strength, so brand colour and any colour-coded state an app
        // encodes in its icon are lost for every tray item, not just misbehaving
        // ones.
        //
        // Turning this off is a supported choice; it is not a fix. With it off,
        // the raw app pixmap is drawn untouched and nothing constrains its
        // brightness: LocalSend advertises a literal `logo-32-white.png` and
        // lands at L≈99%, brighter than any colour in the palette. Per-app
        // substitution (bar.tray.iconSubs) does not help there — LocalSend's SNI
        // id is autogenerated per session so there is no stable key, and the
        // themed icon it would fall back to is near-white too (#f1efeb).
        layer.enabled: Config.bar.tray.recolour
    }
}
